// <auto-generated />
using Cican_Micro.Data;
using Cican_Micro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cican_Micro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180916063215_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cican_Micro.Models.Produits", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categorie");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Modele");

                    b.Property<string>("Nom");

                    b.Property<decimal>("prix");

                    b.HasKey("ID");

                    b.ToTable("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
